# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rprod <- function(v) {
    .Call(`_carat_Rprod`, v)
}

Bpert <- function(bsize = 4L, tr_num = 2L) {
    .Call(`_carat_Bpert`, bsize, tr_num)
}

PStrGen <- function(cov_num, level_num) {
    .Call(`_carat_PStrGen`, cov_num, level_num)
}

Prob_S <- function(cov_num, level_num, pr) {
    .Call(`_carat_Prob_S`, cov_num, level_num, pr)
}

ReturnCol <- function(M, V) {
    .Call(`_carat_ReturnCol`, M, V)
}

MVReturnM <- function(M, MV) {
    .Call(`_carat_MVReturnM`, M, MV)
}

nameString <- function(cov_num, level_num, strt_num, type, AllStrata) {
    .Call(`_carat_nameString`, cov_num, level_num, strt_num, type, AllStrata)
}

BBCDname <- function(n, S = "pat") {
    .Call(`_carat_BBCDname`, n, S)
}

Preprocess <- function(data) {
    .Call(`_carat_Preprocess`, data)
}

genData_sim <- function(n, cov_num, level_num, ProbS) {
    .Call(`_carat_genData_sim`, n, cov_num, level_num, ProbS)
}

HPSOne <- function(D, PStr, cov_profile, cov_num, level_num, omega, strp, p = 0.85) {
    .Call(`_carat_HPSOne`, D, PStr, cov_profile, cov_num, level_num, omega, strp, p)
}

StrROne <- function(D, PS, cov_profile, cov_num, level_num, bsize, B, BG, strp) {
    .Call(`_carat_StrROne`, D, PS, cov_profile, cov_num, level_num, bsize, B, BG, strp)
}

AtBCDOne <- function(D, PStr, cov_profile, cov_num, level_num, F, b, strp, No = 0L) {
    .Call(`_carat_AtBCDOne`, D, PStr, cov_profile, cov_num, level_num, F, b, strp, No)
}

AdBCDOne <- function(D, PStr, cov_profile, cov_num, level_num, strp, a = 2) {
    .Call(`_carat_AdBCDOne`, D, PStr, cov_profile, cov_num, level_num, strp, a)
}

C_HPS <- function(n, cov_num, level_num, ProbS, PStr, omega, p = 0.85) {
    .Call(`_carat_C_HPS`, n, cov_num, level_num, ProbS, PStr, omega, p)
}

C_StrR <- function(n, cov_num, level_num, ProbS, PS, bsize, tr_num) {
    .Call(`_carat_C_StrR`, n, cov_num, level_num, ProbS, PS, bsize, tr_num)
}

C_AtkinBCD <- function(n, cov_num, level_num, ProbS, PS) {
    .Call(`_carat_C_AtkinBCD`, n, cov_num, level_num, ProbS, PS)
}

C_AdjustBCD <- function(n, cov_num, level_num, ProbS, PS, a = 2.0) {
    .Call(`_carat_C_AdjustBCD`, n, cov_num, level_num, ProbS, PS, a)
}

C_RHPS <- function(data_proc, cov_num, level_num, omega, p = 0.85) {
    .Call(`_carat_C_RHPS`, data_proc, cov_num, level_num, omega, p)
}

C_RStrR <- function(data_proc, cov_num, level_num, bsize, tr_num = 2L) {
    .Call(`_carat_C_RStrR`, data_proc, cov_num, level_num, bsize, tr_num)
}

C_RAtkinBCD <- function(data_proc, cov_num, level_num) {
    .Call(`_carat_C_RAtkinBCD`, data_proc, cov_num, level_num)
}

C_RAdjustBCD <- function(data_proc, cov_num, level_num, a = 2.0) {
    .Call(`_carat_C_RAdjustBCD`, data_proc, cov_num, level_num, a)
}

C_Summarize <- function(Replace, cov_num, level_num, pr, method, omega, p, bsize, a, n, N) {
    .Call(`_carat_C_Summarize`, Replace, cov_num, level_num, pr, method, omega, p, bsize, a, n, N)
}

C_RSummarize <- function(data_proc, cov_num, level_num, method, omega, p, bsize, a, N) {
    .Call(`_carat_C_RSummarize`, data_proc, cov_num, level_num, method, omega, p, bsize, a, N)
}

HuHuCAR_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, omega, p) {
    .Call(`_carat_HuHuCAR_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, omega, p)
}

HuHuCAR_RT <- function(data, Reps, conf, omega, p = 0.85) {
    .Call(`_carat_HuHuCAR_RT`, data, Reps, conf, omega, p)
}

HuHuCAR_BT <- function(data, B, omega, p) {
    .Call(`_carat_HuHuCAR_BT`, data, B, omega, p)
}

HuHuCAR_RT_In <- function(data, Reps, omega, p) {
    .Call(`_carat_HuHuCAR_RT_In`, data, Reps, omega, p)
}

HuHuCAR_BT_In <- function(data, B, omega, p) {
    .Call(`_carat_HuHuCAR_BT_In`, data, B, omega, p)
}

HuHuCAR_RT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, omega, p, Reps, nthreads) {
    .Call(`_carat_HuHuCAR_RT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, omega, p, Reps, nthreads)
}

HuHuCAR_BT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, omega, p, B, nthreads) {
    .Call(`_carat_HuHuCAR_BT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, omega, p, B, nthreads)
}

PocSimMIN_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, weight, p) {
    .Call(`_carat_PocSimMIN_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, weight, p)
}

PocSimMIN_RT <- function(data, Reps, conf, weight, p = 0.85) {
    .Call(`_carat_PocSimMIN_RT`, data, Reps, conf, weight, p)
}

PocSimMIN_BT <- function(data, B, weight, p) {
    .Call(`_carat_PocSimMIN_BT`, data, B, weight, p)
}

PocSimMIN_RT_In <- function(data, Reps, weight, p) {
    .Call(`_carat_PocSimMIN_RT_In`, data, Reps, weight, p)
}

PocSimMIN_BT_In <- function(data, B, weight, p) {
    .Call(`_carat_PocSimMIN_BT_In`, data, B, weight, p)
}

PocSimMIN_RT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, weight, p, Reps, nthreads) {
    .Call(`_carat_PocSimMIN_RT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, weight, p, Reps, nthreads)
}

PocSimMIN_BT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, weight, p, B, nthreads) {
    .Call(`_carat_PocSimMIN_BT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, weight, p, B, nthreads)
}

StrBCD_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, p) {
    .Call(`_carat_StrBCD_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, p)
}

StrBCD_RT <- function(data, Reps, conf, p = 0.85) {
    .Call(`_carat_StrBCD_RT`, data, Reps, conf, p)
}

StrBCD_BT <- function(data, B, p) {
    .Call(`_carat_StrBCD_BT`, data, B, p)
}

StrBCD_RT_In <- function(data, Reps, p) {
    .Call(`_carat_StrBCD_RT_In`, data, Reps, p)
}

StrBCD_BT_In <- function(data, B, p) {
    .Call(`_carat_StrBCD_BT_In`, data, B, p)
}

StrBCD_RT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, p, Iternum, sl, Reps, nthreads) {
    .Call(`_carat_StrBCD_RT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, p, Iternum, sl, Reps, nthreads)
}

StrBCD_BT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, p, B, nthreads) {
    .Call(`_carat_StrBCD_BT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, p, B, nthreads)
}

DoptBCD_In <- function(n, cov_num, level_num, pr) {
    .Call(`_carat_DoptBCD_In`, n, cov_num, level_num, pr)
}

DoptBCD_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma) {
    .Call(`_carat_DoptBCD_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma)
}

DoptBCD_RT <- function(data, Reps, conf) {
    .Call(`_carat_DoptBCD_RT`, data, Reps, conf)
}

DoptBCD_BT <- function(data, B) {
    .Call(`_carat_DoptBCD_BT`, data, B)
}

DoptBCD_RT_In <- function(data, Reps) {
    .Call(`_carat_DoptBCD_RT_In`, data, Reps)
}

DoptBCD_BT_In <- function(data, B) {
    .Call(`_carat_DoptBCD_BT_In`, data, B)
}

DoptBCD_RT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, Reps, nthreads) {
    .Call(`_carat_DoptBCD_RT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, Reps, nthreads)
}

DoptBCD_BT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, B, nthreads) {
    .Call(`_carat_DoptBCD_BT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, B, nthreads)
}

AdjBCD_In <- function(n, cov_num, level_num, pr, a = 2) {
    .Call(`_carat_AdjBCD_In`, n, cov_num, level_num, pr, a)
}

AdjBCD_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, a) {
    .Call(`_carat_AdjBCD_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, a)
}

AdjBCD_RT <- function(data, Reps, conf, a) {
    .Call(`_carat_AdjBCD_RT`, data, Reps, conf, a)
}

AdjBCD_BT <- function(data, B, a) {
    .Call(`_carat_AdjBCD_BT`, data, B, a)
}

AdjBCD_RT_In <- function(data, Reps, a) {
    .Call(`_carat_AdjBCD_RT_In`, data, Reps, a)
}

AdjBCD_BT_In <- function(data, B, a) {
    .Call(`_carat_AdjBCD_BT_In`, data, B, a)
}

AdjBCD_RT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, a, Reps, nthreads) {
    .Call(`_carat_AdjBCD_RT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, a, Reps, nthreads)
}

AdjBCD_BT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, a, B, nthreads) {
    .Call(`_carat_AdjBCD_BT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, a, B, nthreads)
}

StrPBR_getData <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, bsize) {
    .Call(`_carat_StrPBR_getData`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, bsize)
}

StrPBR_RT <- function(data, Reps, conf, bsize) {
    .Call(`_carat_StrPBR_RT`, data, Reps, conf, bsize)
}

StrPBR_BT <- function(data, B, bsize) {
    .Call(`_carat_StrPBR_BT`, data, B, bsize)
}

StrPBR_RT_In <- function(data, Reps, bsize) {
    .Call(`_carat_StrPBR_RT_In`, data, Reps, bsize)
}

StrPBR_BT_In <- function(data, B, bsize) {
    .Call(`_carat_StrPBR_BT_In`, data, B, bsize)
}

StrPBR_RT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, bsize, Reps, nthreads) {
    .Call(`_carat_StrPBR_RT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, bsize, Reps, nthreads)
}

StrPBR_BT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, bsize, B, nthreads) {
    .Call(`_carat_StrPBR_BT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, bsize, B, nthreads)
}

CTT <- function(data) {
    .Call(`_carat_CTT`, data)
}

CTT_In <- function(data) {
    .Call(`_carat_CTT_In`, data)
}

HuHuCAR_CT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, omega, p) {
    .Call(`_carat_HuHuCAR_CT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, omega, p)
}

PocSimMIN_CT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, weight, p) {
    .Call(`_carat_PocSimMIN_CT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, weight, p)
}

StrBCD_CT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, p) {
    .Call(`_carat_StrBCD_CT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, p)
}

DoptBCD_CT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl) {
    .Call(`_carat_DoptBCD_CT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl)
}

AdjBCD_CT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, a) {
    .Call(`_carat_AdjBCD_CT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, a)
}

StrPBR_CT_power <- function(n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, bsize) {
    .Call(`_carat_StrPBR_CT_power`, n, cov_num, level_num, pr, type, beta, mu1, mu2, sigma, Iternum, sl, bsize)
}

